export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";
export const SEND_CODE_SUCCESS = "SEND_CODE_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const LOGOUT = "LOGOUT";
export const ADD_REGION_SUCCESS = "ADD_REGION_SUCCESS";
export const ADD_REGION_FAIL = "ADD_REGION_FAIL";
export const ADD_NODE_SUCCESS = "ADD_NODE_SUCCESS";
export const ADD_NODE_FAIL = "ADD_NODE_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
